version: '3.9'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - portfolio-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - portfolio-network

  # Optional: Add a development service with hot reloading
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-dev
    ports:
      - "3000:3000"
      - "35729:35729"  # For react-refresh
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    networks:
      - portfolio-network

  # Optional: Nginx as a reverse proxy and static file server
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  node_modules:
  backend_modules:
